"""empty message

Revision ID: 3e462006e3ad
Revises: 11286858bc00
Create Date: 2022-09-27 15:46:18.933253

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e462006e3ad'
down_revision = '11286858bc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts_transfer_history_09_2022', schema='content')
    op.drop_table('units_transfer_history_09_2022', schema='content')
    op.drop_table('operations_history_09_2022', schema='content')
    op.create_unique_constraint(None, 'operation_products', ['id'], schema='content')
    op.create_unique_constraint(None, 'operations', ['id'], schema='content')
    op.create_unique_constraint(None, 'operations_history', ['id', 'completion_date'], schema='content')
    op.create_unique_constraint(None, 'part_operations', ['id'], schema='content')
    op.create_unique_constraint(None, 'part_sections', ['id'], schema='content')
    op.create_unique_constraint(None, 'part_units', ['id'], schema='content')
    op.create_unique_constraint(None, 'parts', ['id'], schema='content')
    op.create_unique_constraint(None, 'units_transfer_history', ['id', 'transfer_date'], schema='content')
    op.add_column('products', sa.Column('delivery_date', sa.Date(), nullable=False), schema='content')
    op.create_unique_constraint(None, 'products', ['id'], schema='content')
    op.create_unique_constraint(None, 'sections', ['id'], schema='content')
    op.create_unique_constraint(None, 'unit_operations', ['id'], schema='content')
    op.create_unique_constraint(None, 'unit_sections', ['id'], schema='content')
    op.create_unique_constraint(None, 'units', ['id'], schema='content')
    op.create_unique_constraint(None, 'units_transfer_history', ['id', 'transfer_date'], schema='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units_transfer_history', schema='content', type_='unique')
    op.drop_constraint(None, 'units', schema='content', type_='unique')
    op.drop_constraint(None, 'unit_sections', schema='content', type_='unique')
    op.drop_constraint(None, 'unit_operations', schema='content', type_='unique')
    op.drop_constraint(None, 'sections', schema='content', type_='unique')
    op.drop_constraint(None, 'products', schema='content', type_='unique')
    op.drop_column('products', 'delivery_date', schema='content')
    op.drop_constraint(None, 'units_transfer_history', schema='content', type_='unique')
    op.drop_constraint(None, 'parts', schema='content', type_='unique')
    op.drop_constraint(None, 'part_units', schema='content', type_='unique')
    op.drop_constraint(None, 'part_sections', schema='content', type_='unique')
    op.drop_constraint(None, 'part_operations', schema='content', type_='unique')
    op.drop_constraint(None, 'operations_history', schema='content', type_='unique')
    op.drop_constraint(None, 'operations', schema='content', type_='unique')
    op.drop_constraint(None, 'operation_products', schema='content', type_='unique')
    op.create_table('operations_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['content.operations.id'], name='operations_history_operation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['content.products.id'], name='operations_history_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'completion_date', name='operations_history_09_2022_pkey'),
    schema='content'
    )
    op.create_table('units_transfer_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('transfer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['content.units.id'], name='units_transfer_history_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['content.sections.id'], name='units_transfer_history_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['content.sections.id'], name='units_transfer_history_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'transfer_date', name='units_transfer_history_09_2022_pkey'),
    schema='content'
    )
    op.create_table('parts_transfer_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('transfer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['content.parts.id'], name='parts_transfer_history_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['content.sections.id'], name='parts_transfer_history_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['content.sections.id'], name='parts_transfer_history_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'transfer_date', name='parts_transfer_history_09_2022_pkey'),
    schema='content'
    )
    # ### end Alembic commands ###
