"""empty message

Revision ID: cbb85137348c
Revises: 3e462006e3ad
Create Date: 2022-09-28 13:37:37.106197

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbb85137348c'
down_revision = '3e462006e3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units_transfer_history_09_2022', schema='content')
    op.drop_table('parts_transfer_history_09_2022', schema='content')
    op.drop_table('operations_history_09_2022', schema='content')
    op.create_unique_constraint(None, 'units_transfer_history', ['id', 'transfer_date'], schema='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units_transfer_history', schema='content', type_='unique')
    op.create_table('operations_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('operation_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['content.operations.id'], name='operations_history_operation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['content.products.id'], name='operations_history_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'completion_date', name='operations_history_09_2022_pkey'),
    sa.UniqueConstraint('id', 'completion_date', name='operations_history_09_2022_id_completion_date_key'),
    schema='content'
    )
    op.create_table('parts_transfer_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('transfer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['content.parts.id'], name='parts_transfer_history_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['content.sections.id'], name='parts_transfer_history_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['content.sections.id'], name='parts_transfer_history_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'transfer_date', name='parts_transfer_history_09_2022_pkey'),
    schema='content'
    )
    op.create_table('units_transfer_history_09_2022',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('transfer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['content.units.id'], name='units_transfer_history_item_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['content.sections.id'], name='units_transfer_history_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['content.sections.id'], name='units_transfer_history_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'transfer_date', name='units_transfer_history_09_2022_pkey'),
    sa.UniqueConstraint('id', 'transfer_date', name='units_transfer_history_09_2022_id_transfer_date_key'),
    sa.UniqueConstraint('id', 'transfer_date', name='units_transfer_history_09_2022_id_transfer_date_key1'),
    schema='content'
    )
    # ### end Alembic commands ###
